PRAGMA foreign_keys = ON;

INSERT INTO starter_characters
  (id, slug, name, persona, style_prompt, hero_media_id, provider_config_json, sort, status, created_at, updated_at)
VALUES
  ('starter_rowan_parsons_crit', 'rowan-parsons-crit', 'Rowan - Parsons Crit', 'experimental art-school fashion creator with studio critiques, handmade layers, gallery stairwells, and smart downtown styling', 'experimental art-school fashion creator with studio critiques, handmade layers, gallery stairwells, and smart downtown styling, social-first composition, trend-ready lifestyle image', NULL, '{}', 110, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_liora_downtown_muse', 'liora-downtown-muse', 'Liora - Downtown Muse', 'downtown fashion creator with vintage slips, sharp coats, gallery openings, mirror fit checks, and late-afternoon city light', 'downtown fashion creator with vintage slips, sharp coats, gallery openings, mirror fit checks, and late-afternoon city light, social-first composition, trend-ready lifestyle image', NULL, '{}', 120, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_dorian_experimental_dresser', 'dorian-experimental-dresser', 'Dorian - Experimental Dresser', 'experimental menswear creator with sculptural outerwear, wide trousers, unusual proportions, and quiet confidence in city architecture', 'experimental menswear creator with sculptural outerwear, wide trousers, unusual proportions, and quiet confidence in city architecture, social-first composition, trend-ready lifestyle image', NULL, '{}', 130, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_sable_form_study', 'sable-form-study', 'Sable - Form Study', 'form-led fashion creator with monochrome layering, textile closeups, cropped poses, and outfit-first editorial compositions', 'form-led fashion creator with monochrome layering, textile closeups, cropped poses, and outfit-first editorial compositions, social-first composition, trend-ready lifestyle image', NULL, '{}', 140, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_vesper_goth_rap_streetwear', 'vesper-goth-rap-streetwear', 'Vesper - Goth Rap Streetwear', 'goth-rap avant streetwear creator with black leather, oversized silhouettes, silver hardware, night flash, and distorted club-adjacent energy', 'goth-rap avant streetwear creator with black leather, oversized silhouettes, silver hardware, night flash, and distorted club-adjacent energy, social-first composition, trend-ready lifestyle image', NULL, '{}', 150, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_niko_underground_set', 'niko-underground-set', 'Niko - Underground Set', 'underground music fashion creator with basement show fits, worn denim, layered merch, film-grain flash, and post-show street portraits', 'underground music fashion creator with basement show fits, worn denim, layered merch, film-grain flash, and post-show street portraits, social-first composition, trend-ready lifestyle image', NULL, '{}', 160, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_ren_niche_designer', 'ren-niche-designer', 'Ren - Niche Designer', 'niche designer fashion creator with asymmetrical cuts, technical fabrics, quiet Tokyo side streets, and collector-level wardrobe details', 'niche designer fashion creator with asymmetrical cuts, technical fabrics, quiet Tokyo side streets, and collector-level wardrobe details, social-first composition, trend-ready lifestyle image', NULL, '{}', 170, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z'),
  ('starter_mika_archive_layers', 'mika-archive-layers', 'Mika - Archive Layers', 'archive fashion creator with rare jackets, layered skirts and trousers, museum-library textures, and thoughtful outfit breakdowns', 'archive fashion creator with rare jackets, layered skirts and trousers, museum-library textures, and thoughtful outfit breakdowns, social-first composition, trend-ready lifestyle image', NULL, '{}', 180, 'setup_pending', '2026-05-08T00:00:00.000Z', '2026-05-08T00:00:00.000Z')
ON CONFLICT(slug) DO NOTHING;
